// <auto-generated />
using MemberRegister.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemberRegister.Migrations
{
    [DbContext(typeof(MemberDetailContext))]
    partial class MemberDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MemberRegister.Models.MemberDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberMail")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MemberPhone")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("MemberDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
